// Polylang Hub - Verified Translation Science & Academic Resources Library
// Authentic academic references, research lectures, university certificate programs & accredited platforms
// Titles strictly preserved without instructor personal names. Direct access links verified.

const ACADEMY_100_VIDEOS = [
  {
    id: "res_cheni_fairouz_pdf",
    title: "محاضرات في علم الترجمة: قضايا ومقاربات (PDF)",
    category: "academic_lectures",
    categoryLabel: "محاضرات أكاديمية (PDF)",
    format: "PDF Document",
    formatIcon: "📄",
    url: "https://fac.umc.edu.dz/fll/images/cours/CHENI%20FAIROUZ.pdf",
    language: "ar",
    langLabel: "العربية / اللغات الأجنبية",
    duration: "وثيقة أكاديمية معتمدة",
    level: "دراسات جامعية وتخصصية",
    isPremium: false,
    verifiedBadge: "✓ مرجع جامعي معتمد",
    desc: "محاضرات أكاديمية موثقة في علم الترجمة تتناول القضايا والمقاربات النظرية والتطبيقية، ومناهج التحليل والترجمة التخصصية لطلبة الدراسات العليا والمترجمين."
  },
  {
    id: "res_scribd_intro_translation",
    title: "مدخل إلى علم الترجمة (ملف على Scribd)",
    category: "studies_books",
    categoryLabel: "دراسات ومراجع الترجمة",
    format: "Scribd Document",
    formatIcon: "📖",
    url: "https://www.scribd.com/document/600337087/مدخل-إلى-علم-الترجمة",
    language: "ar",
    langLabel: "العربية",
    duration: "مرجع دراسي تأصيلي",
    level: "تأسيسي وأكاديمي",
    isPremium: false,
    verifiedBadge: "✓ دراسة مرجعية موثقة",
    desc: "مرجع علمي تأسيسي يقدم مدخلاً مفصلاً لأسس ونظريات علم الترجمة والمدارس اللسانية والترجمية وتطبيقاتها العلمية في نقل النصوص بين الثقافات."
  },
  {
    id: "res_facebook_translation_basics_1",
    title: "الدرس الأول من سلسلة “أساسيات الترجمة”",
    category: "series_lessons",
    categoryLabel: "سلاسل دروس الترجمة",
    format: "Interactive Lecture",
    formatIcon: "🎓",
    url: "https://www.facebook.com/kogee.elrishi/posts/8070308722982424",
    language: "ar",
    langLabel: "العربية / الإنجليزية",
    duration: "درس تطبيقي منهجي",
    level: "مبتدئ إلى متوسط",
    isPremium: false,
    verifiedBadge: "✓ درس تعليمي منهجي",
    desc: "درس تطبيقي منهجي يشرح الركائز الأساسية لنقل المعنى وتفادي الترجمة الحرفية وضبط التراكيب النحوية والأسلوبية بين اللغات مع تدريبات عملية."
  },
  {
    id: "res_ksu_pptx_intro",
    title: "عرض تقديمي PowerPoint: مدخل إلى علم الترجمة (جامعة الملك سعود)",
    category: "university_slides",
    categoryLabel: "عروض تقديمية جامعية (PPTX)",
    format: "PowerPoint PPTX",
    formatIcon: "📊",
    url: "https://fac.ksu.edu.sa/sites/default/files/_1.pptx",
    language: "ar",
    langLabel: "العربية / اللغات",
    duration: "شرائح عرض أكاديمية",
    level: "جامعي معتمد",
    isPremium: false,
    verifiedBadge: "✓ صادر عن كلية اللغات والترجمة (KSU)",
    desc: "عرض تقديمي شامل ومفصل صادر عن كلية اللغات والترجمة بجامعة الملك سعود يوضح مفاهيم علم الترجمة، أدوات المترجم، واستراتيجيات المعالجة اللغوية."
  },
  {
    id: "res_coursera_translation",
    title: "دورات ترجمة مجانية عبر منصة Coursera",
    category: "online_courses",
    categoryLabel: "دورات عالمية عبر الإنترنت",
    format: "Online University Courses",
    formatIcon: "🌐",
    url: "https://www.coursera.org/courses?query=translation",
    language: "en",
    langLabel: "الإنجليزية / متعدد اللغات",
    duration: "مساقات متعددة مع شهادات",
    level: "متعدد المستويات",
    isPremium: false,
    verifiedBadge: "✓ دورات جامعية دولية معتمدة",
    desc: "باقة منتقاة من المساقات والورش التدريبية المتخصصة في الترجمة واللغات من جامعات دولية رائدة عبر منصة كورسيرا العالمية مع مسارات مجانية وخيارات شهادات إتمام."
  },
  {
    id: "res_umass_amherst_cert",
    title: "شهادة الترجمة والوساطة اللغوية – جامعة ماساتشوستس Amherst",
    category: "academic_degrees",
    categoryLabel: "شهادات جامعية دولية",
    format: "University Certificate Program",
    formatIcon: "📜",
    url: "https://www.umass.edu/languages-literatures-cultures/academics/online-certificate-professional-translation-interpreting",
    language: "en",
    langLabel: "الإنجليزية / متعدد اللغات",
    duration: "برنامج شهادة مهنية معتمد",
    level: "شهادة مهنية احترافية",
    isPremium: false,
    verifiedBadge: "✓ University of Massachusetts Amherst",
    desc: "برنامج أكاديمي ومهني معتمد عبر الإنترنت في الترجمة التحريرية والتفسير الشفوي والوساطة اللغوية من كلية الآداب بجامعة ماساتشوستس أمهرست."
  },
  {
    id: "res_nyu_sps_ms",
    title: "ماجستير في الترجمة والتفسير – جامعة نيويورك (NYU SPS)",
    category: "postgraduate",
    categoryLabel: "دراسات عليا وماجستير",
    format: "Master of Science (MS)",
    formatIcon: "🏛️",
    url: "https://www.sps.nyu.edu/homepage/academics/masters-degrees/ms-in-translation.html",
    language: "en",
    langLabel: "الإنجليزية / لغات الأمم المتحدة",
    duration: "درجة الماجستير المهني (MS)",
    level: "دراسات عليا متقدمة",
    isPremium: false,
    verifiedBadge: "✓ New York University (NYU SPS)",
    desc: "برنامج درجة الماجستير في علوم الترجمة التحريرية والفورية من كلية الدراسات المهنية بجامعة نيويورك، يؤهل للعمل الدبلوماسي والمؤسسات الدولية الكبرى."
  },
  {
    id: "res_hunter_cuny_cert",
    title: "شهادة دراسات الترجمة – كلية Hunter (CUNY)",
    category: "academic_degrees",
    categoryLabel: "شهادات جامعية دولية",
    format: "Continuing Education Certificate",
    formatIcon: "🎓",
    url: "https://continuing-ed.hunter.cuny.edu/certificate-in-translation-studies/",
    language: "en",
    langLabel: "الإنجليزية / الإسبانية واللغات",
    duration: "دبلوم مهني تطبيقي",
    level: "دبلوم مهني متقدم",
    isPremium: false,
    verifiedBadge: "✓ City University of New York (CUNY)",
    desc: "برنامج شهادة دراسات الترجمة من التعليم المستمر بكلية هانتر في جامعة مدينة نيويورك، يركز على مهارات الصياغة التحريرية والمعايير الاحترافية لقطاع الأعمال."
  },
  {
    id: "res_translastars",
    title: "منصة TranslaStars – دورات احترافية في الترجمة أونلاين",
    category: "pro_platforms",
    categoryLabel: "منصات تدريب احترافية",
    format: "Professional Training Platform",
    formatIcon: "⭐",
    url: "https://www.translastars.com/",
    language: "en",
    langLabel: "متعدد اللغات (EN/ES/IT/FR)",
    duration: "ورش ودورات مهنية متخصصة",
    level: "مهني وتطبيقي",
    isPremium: false,
    verifiedBadge: "✓ TranslaStars Specialized Academy",
    desc: "أكاديمية تدريب مهنية متخصصة تقدم دورات عملية للمترجمين في برامج الكات (CAT Tools) وترجمة الفيديو والدبلجة والترجمة الطبية والقانونية والتسويقية."
  }
];

// Compatibility alias for window scope
if (typeof window !== 'undefined') {
  window.ACADEMY_100_VIDEOS = ACADEMY_100_VIDEOS;
}
